# ```fasta.py``` Functions Demonstration

This JupyterNotebook demonstrates how the functions found in ```fasta.py``` work.

In [1]:
from fasta import *

## Downloading FASTA data

```get_seqs_from_fasta``` reads data from a FASTA file and constructs a dictionary from it.

Each entry contains the sequence ID, its chromosome, its start and stop positions, and the sequence.

In [23]:
seqs_dico = get_seqs_from_fasta("Sequence_by_Peaks_1.fasta")

# print info on "seqs_dico", resulting data from get_seqs_from_fasta()
print("information on `seqs_dico`")
print(f"\ttype: {type(seqs_dico)}")
print(f"\tsize: {len(seqs_dico)}\n")


# print example sequence entry
print("ex. first entry")
fst = list(seqs_dico.items())[0]
print(f"\t{fst[0]}")
for x in fst[1].items() :
    if x[0] != "Chromosome" : print(f"\t\t{x[0]}\t\t{x[1]}")
    else : print(f"\t\t{x[0]}\t{x[1]}")

information on `seqs_dico`
	type: <class 'dict'>
	size: 115

ex. first entry
	ChrF_C_glabrata_CBS138_bPeak_1
		Chromosome	ChrF_C_glabrata_CBS138
		Start		16301
		Stop		17151
		seq		TTTCAAACTTTGGTCTTCTGAACCTCTTCCAAGTACAACAGAAATCAAGAGAGCCCACAGTAACGTTTTGTTCTTGCTGACTTACTGGAGTGAATGAATGAGTTGAGATGAAACAACTCCCATGGCCCCCAAACATAACCAAAAGAAAACAGCTTTGTTGAAGTTCTCCAGAAGAAGACTACAGAAGTAACACTCGTTAAAACTGCTATAAAACGTGTAACTGTTGTATGGGACTGCAAAATGGATAAGACTTGGCTTTGCCTTTTCAGCACATTTGCTCTTCAAAGAAATTGAATATCCTTCTATCCAATCAGATCATGAAGACTATGGCTTTGAGATGAGAACGGGGGTGCAATTTGAGTGGTGTGCAGCCAATAAAACAGTAGATCCCGTATTTCAAAAATTGCACCCGGTTTTCTTTTCTCGTTCGTACAGCTCTTTCTGAATTGCACCCTTTTTTCATATGAACTGCAGTGTTACCTAGATCAAGTGGGGGGGTGGCAGGTGGCTATTTCTGCCTTCTACAGCGCTTTTAGTGAACTTTTGCTTTGTTGTAATTGTAGTTGTATTTCTGTGTGTTACGTGAAATACCGTGCCTTTGTCTATCATTCTTTCAGTGGTTTTGCTCGCAGAGATGGGGCATTTTGATCCATTGTGTGTTAAAGCACAGTGGGACCCAGGAATAGTAGAGAGAAGGAAAGTGGGGGAAGGGTAGCAGTGGGGCCGGAAGGAGAACGTTCTATTCTACAGCATATCTTGTTCTGTTCTCCTGAATGATATATTCTCTCCTGCCAGTCTTCTAACTTCGGTTCCATTGAACAATAATGATGTCGTTGCGAGTGGTGAAACTC

## Pre-Processing FASTA data

### Python Lists and Dictionaries

```id_seq()``` reduces the full dictionary to just the sequence id and the sequence.

In [22]:
ids_seqs = id_seq(seqs_dico)
print("information on `ids_seqs`")
print(f"\ttype: {type(ids_seqs)}")
print(f"\tsize: {len(ids_seqs)}\n")

print("ex. first entry")
print(f"\t{list(ids_seqs.items())[0]}")

information on `ids_seqs`
	type: <class 'dict'>
	size: 115

ex. first entry
	('ChrF_C_glabrata_CBS138_bPeak_1', 'TTTCAAACTTTGGTCTTCTGAACCTCTTCCAAGTACAACAGAAATCAAGAGAGCCCACAGTAACGTTTTGTTCTTGCTGACTTACTGGAGTGAATGAATGAGTTGAGATGAAACAACTCCCATGGCCCCCAAACATAACCAAAAGAAAACAGCTTTGTTGAAGTTCTCCAGAAGAAGACTACAGAAGTAACACTCGTTAAAACTGCTATAAAACGTGTAACTGTTGTATGGGACTGCAAAATGGATAAGACTTGGCTTTGCCTTTTCAGCACATTTGCTCTTCAAAGAAATTGAATATCCTTCTATCCAATCAGATCATGAAGACTATGGCTTTGAGATGAGAACGGGGGTGCAATTTGAGTGGTGTGCAGCCAATAAAACAGTAGATCCCGTATTTCAAAAATTGCACCCGGTTTTCTTTTCTCGTTCGTACAGCTCTTTCTGAATTGCACCCTTTTTTCATATGAACTGCAGTGTTACCTAGATCAAGTGGGGGGGTGGCAGGTGGCTATTTCTGCCTTCTACAGCGCTTTTAGTGAACTTTTGCTTTGTTGTAATTGTAGTTGTATTTCTGTGTGTTACGTGAAATACCGTGCCTTTGTCTATCATTCTTTCAGTGGTTTTGCTCGCAGAGATGGGGCATTTTGATCCATTGTGTGTTAAAGCACAGTGGGACCCAGGAATAGTAGAGAGAAGGAAAGTGGGGGAAGGGTAGCAGTGGGGCCGGAAGGAGAACGTTCTATTCTACAGCATATCTTGTTCTGTTCTCCTGAATGATATATTCTCTCCTGCCAGTCTTCTAACTTCGGTTCCATTGAACAATAATGATGTCGTTGCGAGTGGTGAAACTC')

```seq_only``` creates a sequence-only list.

In [25]:
seqs = seq_only(seqs_dico)
print("information on `seqs`")
print(f"\ttype: {type(seqs)}")
print(f"\tsize: {len(seqs)}\n")

print("ex. first entry")
print(f"\t{seqs[0]}")

information on `seqs`
	type: <class 'list'>
	size: 115

ex. first entry
	TTTCAAACTTTGGTCTTCTGAACCTCTTCCAAGTACAACAGAAATCAAGAGAGCCCACAGTAACGTTTTGTTCTTGCTGACTTACTGGAGTGAATGAATGAGTTGAGATGAAACAACTCCCATGGCCCCCAAACATAACCAAAAGAAAACAGCTTTGTTGAAGTTCTCCAGAAGAAGACTACAGAAGTAACACTCGTTAAAACTGCTATAAAACGTGTAACTGTTGTATGGGACTGCAAAATGGATAAGACTTGGCTTTGCCTTTTCAGCACATTTGCTCTTCAAAGAAATTGAATATCCTTCTATCCAATCAGATCATGAAGACTATGGCTTTGAGATGAGAACGGGGGTGCAATTTGAGTGGTGTGCAGCCAATAAAACAGTAGATCCCGTATTTCAAAAATTGCACCCGGTTTTCTTTTCTCGTTCGTACAGCTCTTTCTGAATTGCACCCTTTTTTCATATGAACTGCAGTGTTACCTAGATCAAGTGGGGGGGTGGCAGGTGGCTATTTCTGCCTTCTACAGCGCTTTTAGTGAACTTTTGCTTTGTTGTAATTGTAGTTGTATTTCTGTGTGTTACGTGAAATACCGTGCCTTTGTCTATCATTCTTTCAGTGGTTTTGCTCGCAGAGATGGGGCATTTTGATCCATTGTGTGTTAAAGCACAGTGGGACCCAGGAATAGTAGAGAGAAGGAAAGTGGGGGAAGGGTAGCAGTGGGGCCGGAAGGAGAACGTTCTATTCTACAGCATATCTTGTTCTGTTCTCCTGAATGATATATTCTCTCCTGCCAGTCTTCTAACTTCGGTTCCATTGAACAATAATGATGTCGTTGCGAGTGGTGAAACTC

### Pandas Dataframe

```seqs_info_to_pd()``` converts the Python dictionary into a Pandas Dataframe.

In [34]:
seqs_pd = seqs_info_to_pd(seqs_dico)
display(seqs_pd.head())

print(f"\ninformation on `seqs_pd`")
print(f"\ttype: {type(seqs_pd)}")
print(f"\tsize: {seqs_pd.shape}")
print(f"\tcolumns: {list(seqs_pd.columns)}")

,sequence id,chromosome,start,stop,sequence
0,ChrF_C_glabrata_CBS138_bPeak_1,ChrF_C_glabrata_CBS138,16301,17151,TTTCAAACTTTGGTCTTCTGAACCTCTTCCAAGTACAACAGAAATC...
1,ChrF_C_glabrata_CBS138_bPeak_2,ChrF_C_glabrata_CBS138,632551,633701,CGTTAAAAACTTACCCGGCTACACTAAACTTACCCGGAATTTCAAG...
2,ChrF_C_glabrata_CBS138_bPeak_3,ChrF_C_glabrata_CBS138,15251,15751,AAAATTAATTATTGAGACATTTGCTAGGCAATTGCTAATATCAATC...
3,ChrF_C_glabrata_CBS138_bPeak_4,ChrF_C_glabrata_CBS138,634001,634251,AGAATGTAGGTTTACAAGTAAGAAAGAAAAAAAAAAAAACTTTTTT...
4,ChrF_C_glabrata_CBS138_bPeak_5,ChrF_C_glabrata_CBS138,414101,414401,AAATATCTTTCTGCAATTGGCATCGTTTCAAGTTACAGATTTTCCT...

information on `seqs_pd`
	type: <class 'pandas.core.frame.DataFrame'>
	size: (115, 5)
	columns: ['sequence id', 'chromosome', 'start', 'stop', 'sequence']

In [ ]:
ids_seqs_pd = seqs_pd.drop(["chromosome","start","stop"], axis=1)
display(ids_seqs_pd.head())

,sequence id,sequence
0,ChrF_C_glabrata_CBS138_bPeak_1,TTTCAAACTTTGGTCTTCTGAACCTCTTCCAAGTACAACAGAAATC...
1,ChrF_C_glabrata_CBS138_bPeak_2,CGTTAAAAACTTACCCGGCTACACTAAACTTACCCGGAATTTCAAG...
2,ChrF_C_glabrata_CBS138_bPeak_3,AAAATTAATTATTGAGACATTTGCTAGGCAATTGCTAATATCAATC...
3,ChrF_C_glabrata_CBS138_bPeak_4,AGAATGTAGGTTTACAAGTAAGAAAGAAAAAAAAAAAAACTTTTTT...
4,ChrF_C_glabrata_CBS138_bPeak_5,AAATATCTTTCTGCAATTGGCATCGTTTCAAGTTACAGATTTTCCT...

In [44]:
seqs_only_pd = seqs_pd["sequence"]
display(seqs_only_pd.head())

0    TTTCAAACTTTGGTCTTCTGAACCTCTTCCAAGTACAACAGAAATC...
1    CGTTAAAAACTTACCCGGCTACACTAAACTTACCCGGAATTTCAAG...
2    AAAATTAATTATTGAGACATTTGCTAGGCAATTGCTAATATCAATC...
3    AGAATGTAGGTTTACAAGTAAGAAAGAAAAAAAAAAAAACTTTTTT...
4    AAATATCTTTCTGCAATTGGCATCGTTTCAAGTTACAGATTTTCCT...
Name: sequence, dtype: object