# Phase 1 : Identifiying Biologically Significant Motifs

_note : This demonstration is done with dataset `Sequence_by_Peaks_1.fasta`. Descriptive text on the results may not be applicable with other dataset_

In [1]:
from fasta import *
from seq_process import *
from search_algorithms import *

## Preparation & Pre-Processing

### FASTA Data

This FASTA data was obtained through ChIP-Seq, ensuring that these sequences contained the same (or a similar) DNA-protein binding site, in this case, a transcription factor binding site.  However, what motif (or sub-sequence) that makes up the site is still to be identified.

In [2]:
seqs_dico = get_seqs_from_fasta("Sequence_by_Peaks_1.fasta")
seqs_pd = seqs_info_to_pd(seqs_dico)
display(seqs_pd.head())

,sequence id,chromosome,start,stop,sequence
0,ChrF_C_glabrata_CBS138_bPeak_1,ChrF_C_glabrata_CBS138,16301,17151,TTTCAAACTTTGGTCTTCTGAACCTCTTCCAAGTACAACAGAAATC...
1,ChrF_C_glabrata_CBS138_bPeak_2,ChrF_C_glabrata_CBS138,632551,633701,CGTTAAAAACTTACCCGGCTACACTAAACTTACCCGGAATTTCAAG...
2,ChrF_C_glabrata_CBS138_bPeak_3,ChrF_C_glabrata_CBS138,15251,15751,AAAATTAATTATTGAGACATTTGCTAGGCAATTGCTAATATCAATC...
3,ChrF_C_glabrata_CBS138_bPeak_4,ChrF_C_glabrata_CBS138,634001,634251,AGAATGTAGGTTTACAAGTAAGAAAGAAAAAAAAAAAAACTTTTTT...
4,ChrF_C_glabrata_CBS138_bPeak_5,ChrF_C_glabrata_CBS138,414101,414401,AAATATCTTTCTGCAATTGGCATCGTTTCAAGTTACAGATTTTCCT...

In [3]:
seqs = list(seqs_pd["sequence"])

### Candidate Kmers Generation

Instead of blindly and naively searching through all of the given sequences, first generating candidate motifs and eliminating the ones that do not satisfy the complexity or TA nucleotide propotion criteria can reduce algorithmic complexity.

In [4]:
kmers = candidate_kmers(7, 3, 2, 1)

## Search Algorithms

The next step is to identify which of the theorectically biologically significant candidate motifs are most frequently present within the given sequences. This can be done with a number of different algorithms.

### HashTable

In [5]:
ht = hashtable(seqs, kmers)

In [8]:
df_ht = pd.DataFrame({"kmers":list(ht.keys()),"freqs":list(ht.values())})
display(df_ht.head(5))

     kmers  freqs
0  TGCACCC     21
1  GGGTGCA     17
2  TATTGAA     15
3  TATTTCA     14
4  TTGTATT     13

_Note how the 2nd most frequent kmer is reverse complementary to the 1st most frequent kmer._

### Median String

In [7]:
ms = medianString(seqs, kmers)

In [9]:
df_ms = pd.DataFrame({"kmers":list(ms.keys()),"distances":list(ms.values())})
display(df_ms.head(5))

     kmers  distances
0  ATAGAAA        147
1  ACTATTT        148
2  AAAGATA        149
3  AAATACA        151
4  ATTTACA        153