In [85]:
#GGGTGCA

In [86]:
from seq_process import *
from search_algorithms import *

from fasta import *
from collections import OrderedDict
import pandas as pd

from suffix_trees import STree

In [101]:
kmers = candidate_kmers(7, 3, 2, 1)

In [88]:
seqs = seq_only(get_seqs_from_fasta("Sequence_by_Peaks_1.fasta"))
ht = hashtable(seqs,kmers)

In [89]:
df_ht = pd.DataFrame({"kmers":list(ht.keys()),"freqs":list(ht.values())})
df_ht.head(5)

     kmers  freqs
0  TGCACCC     21
1  GGGTGCA     17
2  TATTGAA     15
3  TATTTCA     14
4  TTGCACC     13

In [90]:
def totalDistance(kmer, sequences) :
    k = len(kmer)
    total_dist = 0

    for seq in sequences :
        dist = [hammingDistance(kmer,seq[i:i+k]) for i in range(len(seq)-k+1)]
        total_dist += min(dist)

    return total_dist

In [91]:
def medianString(seqs:list, kmers:list) :
    return dict(sorted({k:totalDistance(k,seqs) for k in kmers}.items(), key=lambda item: item[1], reverse=False))

In [92]:
medStr = medianString(seqs, kmers)

In [93]:
df_ms = pd.DataFrame({"kmers":list(medStr.keys()),"distances":list(medStr.values())})
df_ms.head(5)

     kmers  distances
0  ATAGAAA        147
1  ACTATTT        148
2  AAAGATA        149
3  AAATACA        151
4  ATTTACA        153

In [95]:
def suffixTrees(sequences) :
    return STree.STree(" ".join(sequences))

In [96]:
st = suffixTrees(seqs)

In [105]:
dict(sorted({k:len(st.find_all(k)) for k in kmers}.items(), key=lambda item: item[1], reverse=True))

{'TGCACCC': 21,
 'GGGTGCA': 17,
 'TATTGAA': 15,
 'TATTTCA': 14,
 'TTGCACC': 13,
 'TTGTATT': 13,
 'TGCACCT': 13,
 'TTTGTAT': 13,
 'GTGCAAT': 13,
 'TATTTGT': 12,
 'GGTGCAA': 12,
 'ATTTGTA': 12,
 'TTATTGA': 12,
 'ACTATTT': 12,
 'TGCAATT': 12,
 'AAACTAT': 11,
 'ATTGAAG': 10,
 'CTGCACC': 10,
 'AAATACA': 10,
 'TATTCAA': 10,
 'TGTTATT': 10,
 'TGTATTT': 10,
 'TGAACAA': 10,
 'TTATTCA': 10,
 'AATTGTA': 9,
 'GTTATCA': 9,
 'ATTTGCT': 9,
 'TTATTCT': 9,
 'TTTATCA': 9,
 'ATAAGAA': 9,
 'AGAAATG': 9,
 'TTGAAGT': 9,
 'ATTTACA': 9,
 'TTTCTGA': 9,
 'TTGTTAT': 9,
 'TGAATCA': 9,
 'AGAAACT': 9,
 'AGAAATA': 9,
 'TTCTTAT': 9,
 'CTCAATT': 8,
 'TTTCAGT': 8,
 'AAGATAA': 8,
 'TCCATTG': 8,
 'CTTAGAA': 8,
 'AGCAAAT': 8,
 'TTCTACA': 8,
 'TTTCACT': 8,
 'GTAGAAA': 8,
 'AGGTGCA': 8,
 'ATTTAGA': 8,
 'ATCACTT': 8,
 'CATTGAA': 8,
 'TGCAGTT': 8,
 'ACTTCAA': 8,
 'TTCTTAG': 8,
 'TTTCTAT': 8,
 'AAGATTA': 8,
 'AGTTAAT': 8,
 'TATCTTT': 8,
 'TTCTATT': 8,
 'GGTGCAT': 8,
 'TTGAACA': 8,
 'TGAAATA': 8,
 'AAGCTAC': 8,
 'AGATGTA': 8,
 'AACAATA': 8,
 'TTGTACT': 8,
 'AACTGCA': 8,
 'AATAAGA': 8,
 'TCTATTT': 8,
 'TTACCAT': 8,
 'AGCTATT': 7,
 'TTAATCA': 7,
 'TTCTATG': 7,
 'AATACAA': 7,
 'CTGATTT': 7,
 'TGAAGTT': 7,
 'AATTGCA': 7,
 'TACAATG': 7,
 'TGCATTA': 7,
 'ATTACAA': 7,
 'ACTGCAA': 7,
 'GCTATTT': 7,
 'ACATTTG': 7,
 'TGAAACA': 7,
 'AATACCA': 7,
 'TCACTTT': 7,
 'ATTTCTG': 7,
 'ATGAAAG': 7,
 'TACAAAT': 7,
 'AAAGCAT': 7,
 'ATAAAGA': 7,
 'TATCAAA': 7,
 'CTTATCA': 7,
 'ATTTCAC': 7,
 'ACAGTAA': 7,
 'ATTAAGA': 7,
 'GAAACTA': 7,
 'ATTGGTA': 7,
 'ACTTTCA': 7,
 'ATTGTAG': 7,
 'AAATGCA': 7,
 'TACAGAA': 7,
 'AGTTTCT': 7,
 'TTAACAT': 7,
 'CAGAAAT': 7,
 'TCAATTG': 7,
 'ATTAGCT': 7,
 'GAAAGTG': 7,
 'CTGCAAA': 7,
 'ATTTGAG': 7,
 'ACAATGG': 7,
 'TGTACAA': 7,
 'GTGCACC': 7,
 'AGCTACA': 7,
 'TATTGTT': 7,
 'TCTTGCA': 7,
 'AGATAAA': 7,
 'TACCATT': 7,
 'AAGAACT': 7,
 'ATTGCAC': 7,
 'AATGCAC': 7,
 'AATAACT': 7,
 'GTATTTC': 7,
 'TCTGATT': 7,
 'TTATCAG': 7,
 'ATTGCAG': 7,
 'TTGAATA': 7,
 'AAAGATA': 7,
 'CAAGTAC': 7,
 'GTCAATA': 7,
 'AATAGAA': 7,
 'CATGAAA': 6,
 'TCAATTA': 6,
 'AGATTGC': 6,
 'CCATTGA': 6,
 'TATTTGA': 6,
 'AAGAATG': 6,
 'CCATTGT': 6,
 'TTATTGT': 6,
 'AATGGTA': 6,
 'CAATTCT': 6,
 'GCAGTTG': 6,
 'AAGATGG': 6,
 'TCACTTG': 6,
 'TTGTAAC': 6,
 'AATCAAG': 6,
 'TACTTCA': 6,
 'AAACTAG': 6,
 'TTTGTCA': 6,
 'GAAGTTG': 6,
 'TATGGTT': 6,
 'GTATTTG': 6,
 'TATGACA': 6,
 'TTTGACA': 6,
 'TGTTACC': 6,
 'GGTGCAG': 6,
 'TTGCTAA': 6,
 'AAATGAG': 6,
 'TTATGTT': 6,
 'TTTATCT': 6,
 'GTTCAGG': 6,
 'CAACTGG': 6,
 'TTACTGC': 6,
 'CCATGAA': 6,
 'GCAAATG': 6,
 'TTTACAT': 6,
 'TAGCAAA': 6,
 'CTTGATA': 6,
 'GCAAATA': 6,
 'TTGCAGA': 6,
 'CATTGTA': 6,
 'TTATCTT': 6,
 'TAGCATT': 6,
 'TGATCTT': 6,
 'AAGAATA': 6,
 'AGTAATT': 6,
 'TCATTAC': 6,
 'CAATGGT': 6,
 'TGGTATT': 6,
 'GCACCCT': 6,
 'ATTTAGT': 6,
 'GCAATTG': 6,
 'TTGATAC': 6,
 'TTGGCAT': 6,
 'TTGTTAC': 6,
 'TACATTT': 6,
 'TAGATTT': 6,
 'TCTACAG': 6,
 'ACAATTA': 6,
 'TTGCAAG': 6,
 'CAGATTT': 6,
 'TTTGTAG': 6,
 'TATTGGT': 6,
 'TAATCAA': 6,
 'TTCTGAT': 6,
 'TATTCTG': 6,
 'ATTACTG': 6,
 'AGATTAA': 6,
 'GTGCATT': 6,
 'ATAACAA': 6,
 'TGCTCAA': 6,
 'ATGGGTA': 6,
 'ATTCTTA': 6,
 'ATGAACA': 6,
 'TTGTCAA': 6,
 'TAATTGA': 6,
 'CGATAAA': 6,
 'GCAGTTA': 6,
 'AGCTCAT': 6,
 'TTCATTG': 6,
 'TACTGCA': 6,
 'TTCTTGA': 6,
 'ATCAGAA': 6,
 'TCATTGT': 6,
 'TTGTAGA': 6,
 'GGCAGTA': 6,
 'TAAATCA': 6,
 'CATTTCT': 6,
 'AACTATT': 6,
 'GCAATCG': 6,
 'TGTCAAA': 6,
 'GATAACA': 6,
 'TGAAAGC': 6,
 'CAGGCTT': 6,
 'CATTTGA': 6,
 'TCTTTAT': 6,
 'TTGTACA': 6,
 'ATGAGTT': 6,
 'GATCTAA': 6,
 'TTAGCTC': 6,
 'TTGATAA': 6,
 'CTGCAGA': 6,
 'TCTTAGA': 6,
 'AGTGGGA': 6,
 'GTTATTG': 6,
 'AAGTCAA': 6,
 'AAAGTCA': 6,
 'ATTGCTT': 6,
 'TTCACTT': 6,
 'AACATTA': 5,
 'GCTTATT': 5,
 'GGAATAG': 5,
 'GTAGCAA': 5,
 'AGGGTGC': 5,
 'AAGTACA': 5,
 'TCATAAA': 5,
 'CTTACAT': 5,
 'TCTGTAC': 5,
 'AAATGTA': 5,
 'GTGCAAA': 5,
 'TTGGTAG': 5,
 'CAAGATC': 5,
 'GTAGAAC': 5,
 'TTTGAGT': 5,
 'TATTCTT': 5,
 'CACCTAT': 5,
 'TATCACT': 5,
 'ATTCTGA': 5,
 'GCCTTGA': 5,
 'TAAGATG': 5,
 'TACAGCT': 5,
 'ATGTTTA': 5,
 'AGACATT': 5,
 'AGTTATC': 5,
 'ATTTCAG': 5,
 'TCAGGAA': 5,
 'ACAATAA': 5,
 'CTTGCAA': 5,
 'CGTTATT': 5,
 'TGTCATT': 5,
 'CATTTGC': 5,
 'CTTGGCA': 5,
 'GAAATGT': 5,
 'TTTATGT': 5,
 'AATTCAC': 5,
 'GTGAAAT': 5,
 'ATTCAAC': 5,
 'ACCAGTA': 5,
 'CTCATTT': 5,
 'GTACAAA': 5,
 'ATTAGAA': 5,
 'TTAGACA': 5,
 'AAGAATC': 5,
 'AAATGTC': 5,
 'CCACTTC': 5,
 'TGCTTAT': 5,
 'CTATCAA': 5,
 'TGCAAAT': 5,
 'ATAGAAA': 5,
 'TAGAAAT': 5,
 'AATAGCT': 5,
 'AGCTTTG': 5,
 'AGCTGAA': 5,
 'TAAGAAT': 5,
 'ATACAGA': 5,
 'ATTCTAA': 5,
 'CCGATAA': 5,
 'ATTAGCA': 5,
 'ATGTCAA': 5,
 'ATAACAG': 5,
 'CACCGAT': 5,
 'TTACAAT': 5,
 'TTGCAAT': 5,
 'TGTAAGA': 5,
 'TCTTGAA': 5,
 'ACCTTAT': 5,
 'TCTGGAA': 5,
 'CACCTGT': 5,
 'AGTGCAA': 5,
 'TGAGCAC': 5,
 'AGATGGG': 5,
 'AGTGATA': 5,
 'ACATTAA': 5,
 'CAAGCTT': 5,
 'ACGTAGA': 5,
 'TGTAGCA': 5,
 'AAATAGT': 5,
 'TTCTGGA': 5,
 'TGATACT': 5,
 'TACTCAA': 5,
 'ATCGGAA': 5,
 'AACTCAA': 5,
 'GAGGGTG': 5,
 'AATTGAG': 5,
 'AGTCAAT': 5,
 'AGCTTAC': 5,
 'TCTATGA': 5,
 'ACTTCCA': 5,
 'ATCAAGA': 5,
 'TATTGCA': 5,
 'CTTTCAT': 5,
 'TTGTCAG': 5,
 'TCAGAAA': 5,
 'CTGTACC': 5,
 'TTTCTAC': 5,
 'ACTCAAA': 5,
 'TTGGTAT': 5,
 'ATAGCAA': 5,
 'ATTTACT': 5,
 'ACTTTGA': 5,
 'TATGGCA': 5,
 'ATGCACC': 5,
 'TAGATCA': 5,
 'TATGTTT': 5,
 'AGCATAA': 5,
 'GTTATTC': 5,
 'TGGGATA': 5,
 'TGAATAA': 5,
 'TTGTAGG': 5,
 'AACAATG': 5,
 'TTCCACG': 5,
 'CGTAGAT': 5,
 'CAATTGT': 5,
 'CTATTTG': 5,
 'CAGTATT': 5,
 'TACTTTG': 5,
 'TTCAATG': 5,
 'TAATTGT': 5,
 'GGCATCG': 5,
 'GAGCTAT': 5,
 'ACAATGC': 5,
 'AGTAAAT': 5,
 'ATGCTTA': 5,
 'AAGTTAT': 5,
 'TCAATGT': 5,
 'ACTATGA': 5,
 'CTGTAAA': 5,
 'GTAATTC': 5,
 'TGCAGAA': 5,
 'GAAGTCG': 5,
 'TATGAAA': 5,
 'AATCAGA': 5,
 'GTGAAAG': 5,
 'ATTGTAA': 5,
 'TCAAGAA': 5,
 'CTTTGCA': 5,
 'ATTAACA': 5,
 'TTGATTA': 5,
 'TAGGATT': 5,
 'ATCTTTG': 5,
 'ATACCAA': 5,
 'AAGCATA': 5,
 'ACCATGT': 5,
 'GAAATAC': 5,
 'CAGTTTA': 5,
 'TTCTGCA': 5,
 'TATCCAA': 5,
 'CAAATGT': 5,
 'CCTTGAT': 5,
 'AACCATG': 5,
 'TAAGTTC': 5,
 'AGTATGA': 5,
 'CTACAGC': 5,
 'GGATAAG': 5,
 'GTTGCAG': 5,
 'TTTCATG': 5,
 'TACCATC': 5,
 'TAGCTCA': 5,
 'TTCATTA': 5,
 'TATTCAC': 5,
 'TTAATGA': 5,
 'AGGACTT': 5,
 'CAATTGC': 5,
 'GTTCTAT': 5,
 'AGATGGT': 5,
 'AGTTCAT': 5,
 'GATAAGG': 5,
 'TCTGATA': 5,
 'ACTTGTA': 5,
 'GAATACC': 5,
 'TTTCAGC': 5,
 'TGACTTA': 5,
 'GTGGGAT': 5,
 'GCACCTG': 5,
 'TAACATT': 5,
 'TTGAATC': 5,
 'ATTCCTG': 5,
 'CTTAGAC': 5,
 'GAATCAC': 5,
 'GATTGCA': 5,
 'AGACAAT': 5,
 'TTGATCT': 5,
 'TATGTCA': 5,
 'TGATTTA': 5,
 'CACGAAT': 5,
 'TCATTGC': 5,
 'TATGGCT': 5,
 'GATTTCA': 5,
 'AATGAAC': 5,
 'ATTGGCA': 5,
 'CACTTTC': 5,
 'TTACTTC': 5,
 'TGCAAGA': 5,
 'ATTGAAC': 5,
 'TCAAGTT': 5,
 'AATTGCT': 5,
 'GCAGGTG': 5,
 'GAAATGC': 5,
 'TCCTGAT': 5,
 'GCATAGA': 5,
 'TGAATAG': 5,
 'TGATCTA': 5,
 'GTTAGAA': 4,
 'ATGAACT': 4,
 'TAAAGTC': 4,
 'TCTAAAG': 4,
 'GCATTGT': 4,
 'AGCATTT': 4,
 'AATAGTC': 4,
 'TGGTTAT': 4,
 'ACGATTA': 4,
 'CAGTTAA': 4,
 'TATGGGT': 4,
 'CGTACAA': 4,
 'GTGATAA': 4,
 'TATGCAC': 4,
 'TTCACGC': 4,
 'GTGAACT': 4,
 'TGCAGGA': 4,
 'CATGTCT': 4,
 'CTCAAAG': 4,
 'ACTGATT': 4,
 'TCCATAG': 4,
 'TCAAAGA': 4,
 'AAGACTT': 4,
 'TGGCATA': 4,
 'TTCGATA': 4,
 'TGGGTAC': 4,
 'TGTACTT': 4,
 'CAACTTC': 4,
 'TATGCTT': 4,
 'TGGCTAT': 4,
 'ATACAAA': 4,
 'TGACAGT': 4,
 'ACTTGTC': 4,
 'GTTCGAT': 4,
 'CAATGTA': 4,
 'CAAAGTG': 4,
 'TTGTATC': 4,
 'TGTAAAG': 4,
 'CCTAAGA': 4,
 'ATTCGTT': 4,
 'AGGTAAT': 4,
 'AATACTT': 4,
 'GAGTAAA': 4,
 'TAACAGA': 4,
 'ACATAGT': 4,
 'ACAAAGT': 4,
 'GATTTAG': 4,
 'CATAGTT': 4,
 'CCATACC': 4,
 'AGCTTTC': 4,
 'AATCGGA': 4,
 'TGAAGTA': 4,
 'AGTCATT': 4,
 'TTCTGAC': 4,
 'TTATGGT': 4,
 'TACAATT': 4,
 'AAACAGT': 4,
 'CAAACTC': 4,
 'TACCATG': 4,
 'CTTCATA': 4,
 'GCTACAA': 4,
 'GCACCTA': 4,
 'CTGTTAG': 4,
 'CTTCATT': 4,
 'ATCTTGG': 4,
 'CTAAGAA': 4,
 'AATTACA': 4,
 'AAGTTGA': 4,
 'TTGATCC': 4,
 'GTTTACA': 4,
 'TGAGCTA': 4,
 'TAACAAT': 4,
 'AATGCTT': 4,
 'TAAAGAT': 4,
 'TGTTTAT': 4,
 'CTACATT': 4,
 'TGACATA': 4,
 'ATTGACC': 4,
 'CTGCATA': 4,
 'GATACTT': 4,
 'AGTATTG': 4,
 'ACAGTTT': 4,
 'CTTCCAC': 4,
 'AGTCTAA': 4,
 'TTGTAAT': 4,
 'AGATCTA': 4,
 'GATTCCT': 4,
 'GTAGATC': 4,
 'GAACTAA': 4,
 'TTGCAGT': 4,
 'TATCGAA': 4,
 'AACTAGC': 4,
 'ATGCAGT': 4,
 'GACAATT': 4,
 'TGTAATT': 4,
 'TGATAAG': 4,
 'GTAAAGA': 4,
 'CTCGCAG': 4,
 'TAACTGC': 4,
 'GTTAATC': 4,
 'CTTGAAC': 4,
 'TTTAGCA': 4,
 'TCATGAA': 4,
 'TTCTGTA': 4,
 'TTCACTA': 4,
 'AAGTTCT': 4,
 'GATTACT': 4,
 'ATGAGCA': 4,
 'TAGTCTT': 4,
 'CTGAATT': 4,
 'ACAAGTA': 4,
 'TTTCATA': 4,
 'ATAAGGA': 4,
 'AGCAATA': 4,
 'GATTGCT': 4,
 'AACTATG': 4,
 'TAGCCAA': 4,
 'TGCAAAC': 4,
 'TGATTAA': 4,
 'ATTTCTA': 4,
 'GTCAAAC': 4,
 'TTGAACT': 4,
 'CTTTGAT': 4,
 'AGAATTA': 4,
 'TTGTAAG': 4,
 'ATAAACG': 4,
 'GTAGATG': 4,
 'TCAAGTG': 4,
 'TAGGTGC': 4,
 'TTTGATA': 4,
 'GCAATAA': 4,
 'AAAGTGC': 4,
 'ATGGTAA': 4,
 'CACCTTC': 4,
 'CAACTTA': 4,
 'GAATTGT': 4,
 'ACGTTCT': 4,
 'GAAGCTA': 4,
 'TTAGCAT': 4,
 'GAAAGTA': 4,
 'ACAAATG': 4,
 'TTAGTCA': 4,
 'ACCGATA': 4,
 'ATGAGCT': 4,
 'ACATGGA': 4,
 'TAACTTC': 4,
 'GTAAACT': 4,
 'GTACAAT': 4,
 'TCACTAT': 4,
 'ACGGCTT': 4,
 'TTTAGTG': 4,
 'GAATAGT': 4,
 'ACGAAAT': 4,
 'TTGACAG': 4,
 'ACTGGGT': 4,
 'AGCATTA': 4,
 'AGCCAAT': 4,
 'GCCTATT': 4,
 'ACCATGA': 4,
 'AGTACCT': 4,
 'TCAAATG': 4,
 'TAGTGAA': 4,
 'TTGGCAG': 4,
 'TATTTCT': 4,
 'AATCACC': 4,
 'ATACCCT': 4,
 'AAACTCA': 4,
 'TAGCTTT': 4,
 'TTCGTTA': 4,
 'TTCAGCT': 4,
 'TGGATCA': 4,
 'TTTGCAC': 4,
 'TCTAAAT': 4,
 'TAAGACT': 4,
 'CTACCAA': 4,
 'AAACTGC': 4,
 'GCATTTC': 4,
 'AGCACTA': 4,
 'ATCTGTT': 4,
 'TTACATT': 4,
 'AACTTCA': 4,
 'TCGTTAT': 4,
 'AGGATTA': 4,
 'TCTAATT': 4,
 'GGTAGCA': 4,
 'AAAGTAC': 4,
 'AGTTCTA': 4,
 'GACATGT': 4,
 'AGAATAA': 4,
 'AGAACTT': 4,
 'TAGAACA': 4,
 'TCTTTAC': 4,
 'ATCTAAG': 4,
 'TTACAAG': 4,
 'TAGGGCA': 4,
 'CTCAGAA': 4,
 'GTACGGA': 4,
 'ACTGTAA': 4,
 'AAGCCGT': 4,
 'TTATCAA': 4,
 'TGCCTAT': 4,
 'TACAAGA': 4,
 'TAAATGA': 4,
 'GTAATCG': 4,
 'TGACTTT': 4,
 'TGGATAA': 4,
 'AATTCTG': 4,
 'TCAAATA': 4,
 'TGCATTT': 4,
 'AGGGTAT': 4,
 'GTACTGG': 4,
 'CCTGTCA': 4,
 'GTTACAA': 4,
 'TAGACAT': 4,
 'AACAATC': 4,
 'AGAATCT': 4,
 'AGGGCAT': 4,
 'GTTGAAT': 4,
 'AAGCTTA': 4,
 'TCACCTT': 4,
 'CACTAAA': 4,
 'GCTTTAT': 4,
 'TTAAGAC': 4,
 'ACGAATA': 4,
 'GATCCTG': 4,
 'ATACAGC': 4,
 'GGTGATC': 4,
 'CCCAGAT': 4,
 'CTGGAAG': 4,
 'TTAGTTG': 4,
 'GTAGCCA': 4,
 'TTCAAGA': 4,
 'TTAGAAT': 4,
 'GCACCTT': 4,
 'ATGGTTA': 4,
 'GCAAGTA': 4,
 'CATTTAC': 4,
 'AAGCAAT': 4,
 'TGTCAAT': 4,
 'GAGTTCA': 4,
 'TGCTAAT': 4,
 'GCAGTTT': 4,
 'ACCTAGA': 4,
 'TCCAGAA': 4,
 'CTAACAA': 4,
 'ATAGTGG': 4,
 'TTATGCT': 4,
 'ACAGCTT': 4,
 'GGACTTC': 4,
 'CATTAGT': 4,
 'GCCATTG': 4,
 'ATTGCTA': 4,
 'GGTGCAC': 4,
 'CAATGCT': 4,
 'TAATGTT': 4,
 'TGGGACT': 4,
 'TCCACGG': 4,
 'AGATAAC': 4,
 'GAACTCA': 4,
 'CATTGTT': 4,
 'AGTGGAT': 4,
 'TTTGACT': 4,
 'ATACTTT': 4,
 'AGATTAC': 4,
 'CCATGCC': 4,
 'TTAAGAT': 4,
 'TGGGTAT': 4,
 'TCAGGTT': 4,
 'ATGTTTC': 4,
 'CATTTGT': 4,
 'GCTCATT': 4,
 'TTCAGTT': 4,
 'AGATTTA': 4,
 'AGTTGAT': 4,
 'AGTTGGA': 4,
 'ACCTATT': 4,
 'GTTGAAG': 4,
 'ATTCCGT': 4,
 'GTTACCA': 4,
 'CTTGATC': 4,
 'GCGTTAA': 4,
 'CAATTGA': 4,
 'GTCATTG': 4,
 'AATTACT': 4,
 'GCAATAC': 4,
 'TCATGTT': 4,
 'CAATAAC': 4,
 'AGAATGT': 4,
 'GTTGCAA': 4,
 'AGGAACT': 4,
 'TGGCATT': 4,
 'AGCAATC': 4,
 'ATTGTCT': 4,
 'TTAGCTT': 4,
 'AATACAG': 4,
 'AACATGA': 4,
 'AAGATCG': 4,
 'GTCATTT': 4,
 'ATTTGCA': 4,
 'GATGGGT': 4,
 'ACAAGAT': 4,
 'AGGCATC': 4,
 'ACTGGCA': 4,
 'GGCAGTT': 4,
 'CTTGTCA': 4,
 'TATGGAA': 4,
 'TTCCATA': 4,
 'GTGCAGG': 4,
 'ACTTCAT': 4,
 'GAGTTTC': 4,
 'GTATGAA': 4,
 'GGTGAAG': 4,
 'AATGCAG': 4,
 'TGCTCAT': 4,
 'TCACCTA': 4,
 'TCGATAA': 4,
 'TCTAAGA': 4,
 'CTTTATC': 4,
 'GAAGTAA': 4,
 'TCTTATT': 4,
 'TGCAGAT': 4,
 'TTACGGT': 4,
 'TTCGAAG': 4,
 'AATGTCA': 4,
 'GTAAATC': 4,
 'TATTCCT': 4,
 'AATAACA': 4,
 'TAACAAG': 4,
 'ACTATCA': 4,
 'TGATACA': 4,
 'ATTGTTA': 4,
 'AAAGATC': 4,
 'CAGATCT': 4,
 'GGTAGAA': 4,
 'AGTAAAC': 4,
 'ATCAAGT': 4,
 'CTCAAGT': 4,
 'AATTCTA': 4,
 'TCTTAGT': 4,
 'CTTTAGA': 4,
 'TAGACAA': 4,
 'AACTTGA': 4,
 'ATTCTGG': 4,
 'CAATGAA': 4,
 'CATTGCT': 4,
 'GAATAAC': 4,
 'CAGTAAA': 4,
 'TTGACTT': 4,
 'TACGGAA': 4,
 'TCATTGA': 4,
 'TGCATAA': 4,
 'TCTTAAT': 4,
 'GATGTAA': 4,
 'AAACTGA': 4,
 'TGCAGTA': 4,
 'ATAAACT': 4,
 'GTAACTC': 4,
 'CGTTTCA': 4,
 'ACAAATA': 4,
 'ATTAACT': 4,
 'AGATTTC': 4,
 'TGTCAGA': 4,
 'TGCGTTA': 4,
 'CAGTTTC': 4,
 'CTGATTA': 4,
 'TTACATC': 4,
 'ATAAAGT': 4,
 'TTCTGAA': 4,
 'TAGTGGG': 4,
 'GCTGTAC': 4,
 'CATTACT': 4,
 'GTTCCAT': 4,
 'AGGTCAA': 4,
 'CTACAAG': 4,
 'AATAGGT': 4,
 'AGTAACT': 4,
 'GCTTATC': 4,
 'GAACTGC': 4,
 'GTTTATG': 4,
 'AGCGTTT': 4,
 'ACTGCAT': 4,
 'CATGGTT': 4,
 'AGACTAT': 4,
 'AATGTTC': 4,
 'GAACAAT': 4,
 'AACTGTA': 4,
 'GATCTGT': 4,
 'ACATGTT': 4,
 'GAAGCTG': 4,
 'TTGCTCA': 4,
 'CCATCTT': 4,
 'TAGCAAC': 4,
 'AGTCGAT': 4,
 'TGTACCT': 4,
 'AACTTGT': 4,
 'CTCCATG': 4,
 'ATCCTGA': 4,
 'AATCTAA': 4,
 'TGTAACT': 4,
 'GCTGTTA': 4,
 'AGTTTAT': 4,
 'ATCACCT': 4,
 'ATTTCGT': 4,
 'TAATCTT': 4,
 'TCAAGTA': 4,
 'AACGGAT': 4,
 'TGATCAC': 4,
 'ATGACAA': 4,
 'AAGACAT': 4,
 'GCATTCC': 4,
 'ATCTTTA': 4,
 'ATTAGGA': 3,
 'AAGGTCA': 3,
 'TGGCAGT': 3,
 'TTGCTTA': 3,
 'CACTCGT': 3,
 'GCTAAAT': 3,
 'CAAGATA': 3,
 'AGTTATT': 3,
 'ATCCTGT': 3,
 'ACTTTAT': 3,
 'AATTCGT': 3,
 'TACTGCG': 3,
 'ACAAGGT': 3,
 'CATTGGT': 3,
 'ACCTGTT': 3,
 'GGCAATA': 3,
 'CAATACT': 3,
 'AGTACCA': 3,
 'TTCAGTA': 3,
 'CTAATGA': 3,
 'AGATCTG': 3,
 'GATTCTT': 3,
 'GCAGTAT': 3,
 'ACAATGT': 3,
 'GAGCTGT': 3,
 'CGTTGCA': 3,
 'CATTTAG': 3,
 'AGCCGTT': 3,
 'TCTGTAG': 3,
 'TCAACTT': 3,
 'CTATGTC': 3,
 'TAACAGG': 3,
 'TCACGTT': 3,
 'TCAAGAT': 3,
 'ATAGTCA': 3,
 'TAAACAT': 3,
 'AGAATGC': 3,
 'CATCTAC': 3,
 'ATCTTAG': 3,
 'TTGGCAC': 3,
 'ACTATGG': 3,
 'AACGTAT': 3,
 'AAGATGT': 3,
 'GTTTATC': 3,
 'CAATTAC': 3,
 'TTGTAGC': 3,
 'ACTTATC': 3,
 'CACTATG': 3,
 'AGTATCT': 3,
 'TGTAGAA': 3,
 'TCGTACA': 3,
 'GCAAGAT': 3,
 'GCTTAGA': 3,
 'ACTAATT': 3,
 'TTCCAGA': 3,
 'TGGCCAC': 3,
 'CTTAGTT': 3,
 'CAAGATG': 3,
 'GATAAAC': 3,
 'TGCTTAG': 3,
 'AAACATC': 3,
 'GTAATTG': 3,
 'TTCAACT': 3,
 'ACAAGCT': 3,
 'CACCCGT': 3,
 'ATGACTT': 3,
 'ACAATAG': 3,
 'TGTAGCC': 3,
 'GCTTGAA': 3,
 'ACAGGCT': 3,
 'GTTGAGC': 3,
 'CAAGTTC': 3,
 'GTATGAC': 3,
 'CTGCACG': 3,
 'ATGTTCA': 3,
 'TTACTGA': 3,
 'TGAGTTT': 3,
 'AGCCTTA': 3,
 'AAAGTGA': 3,
 'ATAACTG': 3,
 'AGGTCTT': 3,
 'GTGATAG': 3,
 'ACCAATA': 3,
 'CAACCTG': 3,
 'TATCAGA': 3,
 'TGATAGC': 3,
 'AGTTGCT': 3,
 'ACTTTGC': 3,
 'GTAGCCG': 3,
 'ATAGGTT': 3,
 'AAGTTCA': 3,
 'CTTCAAT': 3,
 'CGAAACT': 3,
 'GTTCATA': 3,
 'GACATGG': 3,
 'TGGAAGC': 3,
 'GCTTACA': 3,
 'ATACAGT': 3,
 'CAGTAAT': 3,
 'AAGATCT': 3,
 'TAGCCCT': 3,
 'CAGGTGC': 3,
 'GTACCTG': 3,
 'TACAAAG': 3,
 'ATCTAAC': 3,
 'ATCAGTA': 3,
 'TTACAGA': 3,
 'AGTCAAC': 3,
 'AATGAGC': 3,
 'CACCCTC': 3,
 'ATGCCTA': 3,
 'AAATAGA': 3,
 'CTTATCG': 3,
 'TGTTCTA': 3,
 'CAAAGAT': 3,
 'TATGCAG': 3,
 'TTTCTAG': 3,
 'TTAACTC': 3,
 'TCAGTTT': 3,
 'TCTAGGG': 3,
 'GGGTATC': 3,
 'CCGCACT': 3,
 'CTCCATT': 3,
 'TACCAGC': 3,
 'CTTGTAT': 3,
 'GTTCATT': 3,
 'GTCAGAT': 3,
 'TCCATGT': 3,
 'AATACGT': 3,
 'TTACGTT': 3,
 'CTTACAA': 3,
 'GCATAAA': 3,
 'GATTGTA': 3,
 'AATAGAC': 3,
 'TTTACTC': 3,
 'ATACCGT': 3,
 'ATTTAGC': 3,
 'CTTGTAA': 3,
 'TCATTTG': 3,
 'TAGCTGG': 3,
 'AAACATA': 3,
 'TCTATTG': 3,
 'GGAGCTG': 3,
 'ACTGAGG': 3,
 'TACTCCA': 3,
 'CTGCATT': 3,
 ...}

In [98]:
kmers

'GGTCCGA'